name: flutter_boilerplate
description: A Flutter project with feature-based folder structure and utilities.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  dio: ^5.9.1
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  flutter_secure_storage: ^10.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  firebase_analytics: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
